language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - int
  - test
deploy:
  provider: heroku
  api_key:
    secure: jVKNrfb1MSFPmYsVrb7wsBm1geFeAG2tpxs/DLsp9FgDKJ8EHrkIwci7/1eQEVAodlu4SkImTBCy/uLbOoXsieWeGjhElfEukKeJDr53eKMOs4by7hiYx1KT35rP06QxNkokvM1+0hukxJena+SzvXb9GJPyOPzsiITdVSrU23VyT5yVQ/osdb5/5He798pAuNOv5tynn0Emr3hiTslNEYbN7ssrORvP9jhEUZ/o3RsAz6BP1jZ1rUcIIeNypzW/BVC67AUSmfRRc1w4N7yZkMYvU9ETji+fWgiTn7kpGgzcGsksxTdQS5Tza+kT1RLPYV9V2iDBwi5hhVRuaqtwDsSiW2J4KGykGT41WVKQOpybgbCrZFvpgwhJ45gQo5pW/Eo3fkh5QmvcKBGB4WBCBa0vqnD79sZPHsd9juevmRBVYWLS3sznr/nvR45oohFRvZHPNWJ13UPgarPNGf4DaZuP+JeOS2GTi3wG4gto+B2sg1qixhAQgdXl+oEcBD3sgORDh+qKEORKU0TXHOt5Lms7Zw+vwvZW2xldkvqClqGieKJa20T5oWWNisyE1sH+1lJzlpO0hEUUBGAiBpMF8mQTwHzCXXQeF6Y1O63Gn9rXi1pjI2oOCKan1bqVXdM8t8i7r5kteqUqrDV1sZkMDRoTvUrU/5Huk3oZDX0uEuc=
  app:
    int: todo-rest-staging
    master: todo-rest-production
